---
- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:

    - name: install nginx
      apt: 
        name: nginx 
        update_cache: yes    
# update_cache is the same as running apt update on a debian system

    - name: copy nginx config file
      copy: 
        src: files/nginx.conf 
        dest: /etc/nginx/sites-available/default

    - name: enable configuration
      file:
        dest: /etc/nginx/sites-enabled/default
        src: /etc/nginx/sites-available/default
        state: link

    - name: copy index.html
      template: 
        src: templates/index.html.j2 
        dest: /usr/share/nginx/html/index.html
        mode: 0644

    - name: restart nginx
      service: 
        name: nginx 
        state: restarted
...
